### ISSUE TITLE
Add a timeout to the mutation test runner

### ISSUE THREAD

**Issue by davidlibland** [EvanKepner/mutatest#16]
Certain mutations will cause tests to enter infinite loops (e.g. `while n < 5:` -> `while True:`).
We should add a timeout to prevent that. Mutations which cause timeouts should be logged separately.

This shouldn't be difficult to do. I have a (concept) branch which contains a basic implementation of it (https://github.com/davidlibland/mutatest/tree/feat/timeout).

**Comment by EvanKepner** [comment]
This sounds like a great feature to add. We'll have to think about the logic for naturally slow tests - you can see a few within `mutatest` that I've put `pytest.mark.slow` on, those may exceed the timeout setting but are not actually timeouts. If you feel good about the progress feel free to open an early PR and we can iterate on review that way too.

**Comment by EvanKepner** [comment]
https://github.com/EvanKepner/mutatest/pull/18
