### ISSUE TITLE
Mutatest Raises An Exception In Some Cases

### ISSUE THREAD

**Issue by aaghamohammadi** [EvanKepner/mutatest#24]
Hello,
First of all, thank you for this great tool.
I have run Mutatest for a few projects and it works well. However, in some cases, during mutation trials, exceptions raised. Take the `httipie` project as an example, the exception is:

```
2020-03-07 07:27:26,311: Current target location: utils.py, LocIndex(ast_class='BinOp', lineno=45, col_offset=9, op_type=<class '_ast.LShift'>, end_lineno=None, end_col_offset=None)
Traceback (most recent call last):
  File "/home/ubuntu/lfc/httpie/venv/bin/mutatest", line 10, in <module>
    sys.exit(cli_main())
  File "/home/ubuntu/lfc/httpie/venv/lib/python3.7/site-packages/mutatest/cli.py", line 734, in cli_main
    main(args)
  File "/home/ubuntu/lfc/httpie/venv/lib/python3.7/site-packages/mutatest/cli.py", line 783, in main
    src_loc=src_loc, test_cmds=args.testcmds, config=config
  File "/home/ubuntu/lfc/httpie/venv/lib/python3.7/site-packages/mutatest/run.py", line 614, in run_mutation_trials
    trial_runner=create_mutation_run_trial,
  File "/home/ubuntu/lfc/httpie/venv/lib/python3.7/site-packages/mutatest/run.py", line 526, in mutation_sample_dispatch
    mutant_operations.remove(ggrp_target.loc_idx.op_type)
KeyError: <class '_ast.LShift'>
```
Because of randomness I dont know when that happens. I hope the aformentioned exception will help.

**Comment by EvanKepner** [comment]
@aaghamohammadi thanks for using `mutatest`, and for taking the time write this up. It's definitely a bug, and a bias from testing where the `<<` and `>>` (`ast.LShift` and `ast.RShift`) operators are rare. I've pushed a commit to the `dev` branch linked in an open PR. If you're comfortable installing from a git clone of this repo of that branch I'd be interested in knowing if this patch fixes your issue before writing out tests and publishing a release.

For reference, if you specify `-r 123` you'll get repeated trials for the same inputs with the random seed, and you can use `--debug` if you ever want verbose logging output.

**Comment by EvanKepner** [comment]
My testing source file is (using an empty test file):

```python
def my_func():
    x = 256 << 2
    y = 256 >> 2
    return(x, y)
```

Without the patch, I'm seeing the same KeyError, with it applied things operate as expected.

**Comment by aaghamohammadi** [comment]
Sure. I'll give it a shot.

**Comment by aaghamohammadi** [comment]
I have tried the ```dev``` branch and yes. It seems to work well.

**Comment by aaghamohammadi** [comment]
I found another one!
I tried Mutatest on the `venture` project. The output of `mutatest -s vulture -t "pytest" -r 3` is:
```
2020-03-08 14:22:34,655: Current target location: core.py, LocIndex(ast_class='BinOp', lineno=338, col_offset=32, op_type=<class '_ast.BitOr'>, end_lineno=None, end_col_offset=None)
Traceback (most recent call last):
  File "c:\users\alireza\anaconda3\envs\vulture\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alireza\anaconda3\envs\vulture\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alireza\Anaconda3\envs\vulture\Scripts\mutatest.exe\__main__.py", line 7, in <module>
  File "c:\users\alireza\anaconda3\envs\vulture\lib\site-packages\mutatest\cli.py", line 734, in cli_main
    main(args)
  File "c:\users\alireza\anaconda3\envs\vulture\lib\site-packages\mutatest\cli.py", line 783, in main
    src_loc=src_loc, test_cmds=args.testcmds, config=config
  File "c:\users\alireza\anaconda3\envs\vulture\lib\site-packages\mutatest\run.py", line 614, in run_mutation_trials
    trial_runner=create_mutation_run_trial,
  File "c:\users\alireza\anaconda3\envs\vulture\lib\site-packages\mutatest\run.py", line 526, in mutation_sample_dispatch
    mutant_operations.remove(ggrp_target.loc_idx.op_type)
KeyError: <class '_ast.BitOr'>
```

**Comment by EvanKepner** [comment]
Cool, thanks for testing and helping to improve `mutatest`!

I've added a new test file that covers the basic of all mutation operation types. `ast.BitOr` should also be fixed by the prior patch in the `dev` branch. If you are interested, this is the new test file: https://github.com/EvanKepner/mutatest/pull/25/files#diff-ec143aceb765968257aed36bdd936d48

Given that, I believe all KeyError test cases are covered. I'll likely get this packaged up into a release sometime this week. In the meantime, feel free to use `dev` and if you find any existing corner cases please consult the test file to note where the missing operation type is.

**Comment by aaghamohammadi** [comment]
Sure. I need to run Mutatest a lot because of my research. If I come across any issue, I'll let you know.

**Comment by EvanKepner** [comment]
Sounds great, I'd be interested in knowing more about your research topic and usage of `mutatest` if you are able to share. It's always good to learn about how the tool is used by others. 

I'm going to close this issue, the bug fix is now released in 3.0.1 - https://github.com/EvanKepner/mutatest/releases/tag/3.0.1 - it's available on PyPI and usually takes a day or two to appear on conda-forge.

Thanks again for identifying and writing up the issue!

**Comment by aaghamohammadi** [comment]
My research is about assessing test suite effectiveness (by introducing a new coverage metric). Mutation testing is a great way to assess the effectiveness of test cases, but it is time-consuming. Other coverage-based criteria such as line coverage and branch coverage can be computed quickly. However, they are not as good as mutation testing. For example, LC for Django and Flask are 77% and 90% respectively. Mutation Coverages for those are 55% and %50. As you can see, LC  for Django is more than Flask, but the MC is lower.  The question is :
Is there any coverage metric that can be computed as fast as possible and has a high correlation with Mutation Coverage. Unfortunately, my idea didn't work (correlation was not high enough).

**Comment by EvanKepner** [comment]
That's cool, the slowness of mutation testing is a difficult reality. I've tried to address it here a few ways: 

1. Random sampling within coverage - if the goal is "are tests adequate" then an appropriately sized random sample is (within the covered lines) should give you a sense of that. 
2. Category selection - I may care more about certain categories e.g., comparison operators, than others. Filtering just to that category restricts the space. 
3. Running mode - determines whether or not to try all mutations for an operator, try until the first failure, or just assume if one succeeds then all will succeed. It's a heuristic to again limit the sample space. 
4. Parallel trials - on Python 3.8 the pycache can be put into an alternate directory which enables multiprocessing. 
5. I haven't been able to address it, but in the future a "who tests what" capability to limit the selected tests would also increase speed.

There is a big hurdle to jump with false positives - on a per project basis it could be useful to keep a local database of lines/locations/hashes-of-code to flag false positives. Things like mutation of string concatenation using the addition operator are meaningless and should be skipped all the time.

There is also the instances of operator overloading - things like `pathlib` and `numpy` though I haven't inspected the AST closely to know if those end up as different grammar attributes.

Good luck with the research, and thanks for using `mutatest`!
