### ISSUE TITLE
[Feature Request] Ignore single line by using comment

### ISSUE THREAD

**Issue by KaceCottam** [EvanKepner/mutatest#31]
Hi, I really like the library so far!

I would like to suggest a feature for ignoring mutation of a single line in a file by using something like a comment.

This feature would be useful in cases where modifying a line may change a filesystem during a test. I would like to present to you my specific use case:

```py
def initialize_database(name: str) -> TinyDB:
  return TinyDB(name) if name != ':memory:' else TinyDB(storage=MemoryStorage)
```

In this case, I don't want a file named `:memory:` to be created when running tests, so I would like to ignore this line for the purpose of mutations.

I have seen some other libraries implement a solution that requires a comment such as
```py
def initialize_database(name: str) -> TinyDB:
  return TinyDB(name) if name != ':memory:' else TinyDB(storage=MemoryStorage) # pragma : no mutation
```

Would this be possible to do for metatest?

Cheers.

**Comment by EvanKepner** [comment]
Thanks for testing out `mutatest` and for your suggestion. For large codebases, mutation targets are a random sample out of a large population of potential targets, it's not clear that line-level annotations are pragmatic. I'd suggest test sub-selection  in a way that skips parts of your code where you don't want mutations. By default, `mutatest` only considers "covered" code from the test suite for the random sample.
