### ISSUE TITLE
Python 3.9+ Support

### ISSUE THREAD

**Issue by roma-glushko** [EvanKepner/mutatest#33]
Any plans to support Python 3.9+ in mutatest?

The library is failing at the installation phase due to coverage version restrictions:

<img width="977" alt="Screenshot 2022-12-26 at 19 44 09" src="https://user-images.githubusercontent.com/9402690/209572595-caabfb95-a7ff-4953-af10-2030ca786c71.png">

**Comment by EvanKepner** [comment]
Not at this time - the Python AST changes enough between each version that it's non-trivial to make that switch. Supporting 3.7 and 3.8 when this was created required accounting for those differences, see the mixing defined in the transformer module as an example: https://github.com/EvanKepner/mutatest/blob/45606314e597516c4b26b51e27daeb02e503c292/mutatest/transformers.py#L561-L609
