### ISSUE TITLE
Feature Request: Improve options when running with parallel to prevent timeouts

### ISSUE THREAD

**Issue by ghost** [EvanKepner/mutatest#35]
I've found that the 'parallel' option makes it more likely for tests to timeout.

I have two suggestions to help with this.  First would be to allow users to set the number of parallel processes in command line.  This is especially helpful in situations with shared CPU resources.  For example, one of the places where I can run CICD pipelines is hosted in Kubernetes, and mutatest can see there are 18 CPUs.  However, my pipeline is throttled to 5 CPUs.

Second would be an option to set a minimum timeout on tests.  For example, if a test case initially ran in 2ms.  But then the mutation test took 20ms, it will timeout unless you give a factor of at least 10.  In cases where you are using shared CPU space, short delays like this can occur as CPU is throttled.

Proposal: 
1. Add an optional argument to `--parallel` (or a new option) that indicates maximum number of parallel tests.
2. Add new option `--timeout_minimum INT` that specifies mutatest will always wait at least this number of miliseconds before marking a test as 'TIMEOUT'

Example command:
`mutatest --parallel 4 --timeout_factor 10 --timeout_minimum 500`

**Comment by EvanKepner** [comment]
You can achieve this result outside of `mutatest` - the parallelization is using the pycache environment variable and subprocess. You could script this with your own CPU limits and specify specific tests for each CPU to avoid duplication, setting the pycache variable per shell. Since this can be controlled outside of `mutatest` it does not need to be included as a feature.

**Comment by ghost** [comment]
Do you have any references on how to set that variable?  I'm not seeing anything in subprocess documentation showing that it uses environment variables for that.

**Comment by EvanKepner** [comment]
https://github.com/EvanKepner/mutatest/blob/3a2d14536f49bd4e8511474cadecd47d2a0c2f3b/mutatest/run.py#L458-L468
